### ISSUE TITLE
Other software

### ISSUE THREAD

**Issue by DogancanYr** [bropines/Deeplx-vercel#1]
Is it possible to use it elsewhere than Ballon Translator?

**Comment by bropines** [comment]
> Is it possible to use it elsewhere than Ballon Translator?

Yes. I'm just one of the BT contributors. It has the same API as Deeplx from OwO-Network. You can check the API here
https://deeplx.owo.network/endpoints/free.html

Accordingly, the endpoint will always be like this:
`https://your-deployment-url/api/translate`

**Comment by bropines** [comment]
> Can you recommend an application that I can easily translate with DeepLX ?

They say immersive translate (sort of like a browser extension) has deeplx support. and so it can be embedded in any application. and it's stupid to send requests if you write how. I can look for projects for you if you tell me for what purposes you want to take deeplx.

**Comment by bropines** [comment]
[Immersive translate](https://deeplx.owo.network/integration/immersive-translate.html)

[Bob] (https://deeplx.owo.network/integration/bob.html)

And in general, there is a chat in tg in which sometimes useful things also pop up.

https://t.me/+8KDGHKJCxEVkNzll

**Comment by DogancanYr** [comment]
I am looking for something like write to translate since the site has a 5000 word limit.

**Comment by bropines** [comment]
> Looking for something like write to translate since the site has a 5000 word limit.

In fact, we make similar requests to the site, but using the methods described in the original repository. Try to divide a large text into chunks and translate sequentially. I was struggling with the same problem with Yandex, I had to do chunks.

**Comment by DogancanYr** [comment]
😓😭    👍
