### ISSUE TITLE
Not work today

### ISSUE THREAD

**Issue by bwy727** [bropines/Deeplx-vercel#3]
Today the serve does not work.

**Comment by bropines** [comment]
![image](https://github.com/user-attachments/assets/2245309e-c893-46ff-bf1f-01694cf9108b)

Maybe you are within the EU, there are strict rules about cookies there. Try it with a VPN. If it doesn't help I'll still finish the debug mode though

**Comment by bropines** [comment]
How did you try it?

**Comment by bwy727** [comment]
> How did you try it?

The settings I configured earlier aren't working today. But after resetting with the deployment button, everything's running smoothly. There are no problems now. Thank you!

**Comment by bropines** [comment]
Okay, have a nice day
